services:
  - type: web
    name: smart-trolley
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: FLASK_ENV
        value: production
